name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  build:
    strategy:
      matrix:
        repo:
          - spaceporn
        os:
          - ubuntu-latest
          - windows-latest
        zig_opts:
          - ''
          - '-Ddev'
          - '-Dturbo'
    runs-on: "${{ matrix.os }}"
    steps:
    - uses: tiawl/spaceporn-action-ci@43df9f0e7253ba1ada2ff1882a5ac636be43d4eb
      with:
        repository: "${{ github.repository }}"
        additional_zig_opts: "${{ matrix.zig_opts }}"
        sha: "${{ github.event.pull_request.head.sha }}"
        user: "${{ matrix.repo }}"
        token: "${{ github.token }}"
        test_build: 'true'
        test_update: 'false'
        test_fetch: 'false'
